### ISSUE TITLE
show error when run 'python init.py'

### ISSUE THREAD

**Issue by wzlee** [meanstrong/pydelo#1]
![image](https://cloud.githubusercontent.com/assets/4182865/14759519/3ca5313e-0959-11e6-9f66-07908fdae7db.png)

**Comment by meanstrong** [comment]
It say，you need to install some required packages.

Requirements

Bash(git, rsync, ssh, sshpass)
MySQL
Python
Python site-package(flask, flask-sqlalchemy, pymysql, paramiko) # 建议使用virtualenv来部署
That's all.
