### ISSUE TITLE
安装过程中的几个问题

### ISSUE THREAD

**Issue by wubinhong** [meanstrong/pydelo#3]
- requirement.txt
  增加requirement.txt，方便安装（已经有人提过，希望尽快fixup）
-  No module named 'controller'
  可能是我用的是python3的缘故，是否可以修改web.**init**.py

``` python
from controller import api, login, deploys, project, host, users
```

-->

``` python
from .controller import api, login, deploys, project, host, users
```
- Column 'apikey' cannot be null<br>
  user.apikey这个字段是非空，在init.py中是否可以指定一个默认的apikey？如：

``` python
users.create(name="root",
password="123456", apikey='11111')
```
- 可否支持python3？

**Comment by meanstrong** [comment]
谢谢您的建议。
第1、2两个都已经添加。
第3点是我的init写了之后没有验证，也已经修改
关于python3的支持，我会尽快做的。

**Comment by meanstrong** [comment]
@wubinhong python3的支持我也更新了一下代码。

**Comment by wubinhong** [comment]
@meanstrong 非常感谢！我后期也想搞一个基于python的发布系统，其实主要是关于J2EE的，之前有参考过walle的，可惜这个貌似主要针对php的支持，我checkout下来用了一段时间很是恼火，所以后面有时间我想自己写一个，在github上看到你写了一个，我想在这个基础上fork一个自己的分支，后边希望跟你多多交流！
